# This is a config for E2B sandbox template.
# You can use template ID (i1sfxo816nw0oein0bh7) or template name (autod-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("autod-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("autod-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('autod-nextjs-test')

team_id = "898a65f8-84ab-4618-862d-ac07c1fc0cbb"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "autod-nextjs-test"
template_id = "i1sfxo816nw0oein0bh7"
